# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Site settings
title: "zemna blog"
email: zemna@zemna.net
description: > # this means to ignore newlines until "baseurl:"
  zemna's Blog gives useful information about software programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.zemna.net" # the base hostname & protocol for your site

excerpt_separator: <!--more-->

# Contacts
author: "zemna"
email: "zemna@zemna.net"
github: "https://github.com/zemna"
facebook: "https://www.facebook.com/zemnanet" 

# Build settings
exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
permalink: /:categories/:slug/
lsi: false # If set to true generate related posts

# Outputting
paginate: 5
paginate_path: /page:num/
destination: public

highlighter: rouge

# Facebook Sharing
facebook_app_id: 632837843538038