# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zemna's Blog
email: zemna@zemna.net
description: > # this means to ignore newlines until "baseurl:"
  zemna's Blog gives useful information about software programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.zemna.net" # the base hostname & protocol for your site
twitter_username: zemna
github_username:  zemna

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "zemna"